name: Run Tests

on:
  push:
  schedule:
    - cron: '6 6 * * *'

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Go mod tidy
        run: go mod tidy

      - name: Go run tests
        run: go test -cover ./...
